### ISSUE TITLE
Export/serialize feature

### ISSUE THREAD

**Issue by 0xjjpa** [cloudflare/zkp-ecdsa#15]
Once the `zkAttestProof` object has been created, it would be great to export or serialize it to be able to use it in separate mediums. However, the class object is [fairly complex](https://github.com/cloudflare/zkp-ecdsa/blob/main/src/zkpAttestList.ts#L29-L61), and de/reconstructing seems like a bit of a challenge.

Are there any interest in adding this feature? For the [current use case that seems to be used](https://blog.cloudflare.com/making-phishing-defense-seamless-cloudflare-yubico/), it could be used as "backup" proof in case the generated key has been lost.

**Comment by armfazh** [comment]
The library already has auxiliary functions to perform JSON serde operations.

https://github.com/cloudflare/zkp-ecdsa/blob/d2189b8ccd2b8b627242ac106bba125b6d33279f/src/serde.ts#L21

You can see at this line the test that covers serde code. 

https://github.com/cloudflare/zkp-ecdsa/blob/d2189b8ccd2b8b627242ac106bba125b6d33279f/test/zkpAttestList.test.ts#L45
