### ISSUE TITLE
Questions about `generateParamsList` and `SystemParametersList`...

### ISSUE THREAD

**Issue by bmdelacruz** [cloudflare/zkp-ecdsa#18]
I see that the `secLevel` parameter of `generateParamsList` controls the number of items of the `SignatureProofList.expProof` therefore affects the proving time and the size of the proof. Are `secLevel`s less than 80 safe to use? What's the trade off for proofs created with `secLevel` that are less than 80?

Do provers need to generate a `SystemParametersList` every time they're proving something? If not, is `SystemParametersList` like a snark verification key, i.e. generated only once for each circuit?

**Comment by armfazh** [comment]
The parameters are generated according to the Pedersen commitment scheme, so it follows the same properties as of that scheme.

About the secLevel, this depends on the application. For the application of interest of the paper (see [Page 12](https://eprint.iacr.org/2021/1183.pdf)), paper states that it is admitted this trade off between soundness and performance.
